const actionlist = [
  {
    lookup: "attack",
    name: "Normal Attack",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/attack.png",
    description: "<p>A spell, physical, or combo attack flavored by your mastery.</p><p>On a natural 100, double your total after adding modifiers.</p>",
    dice: "1d100 + modifiers",
    roll: "?r attack  <span class='masteryreplace'> MR </span>  WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "recover",
    name: "Recover",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/recover.png",
    description: "<p>Recover HP.</p>",
    dice: "1d20",
    roll: "?r recover # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "rush",
    name: "Rush",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/rush.png",
    description: "<p>You focus all your effort into moving. Gain 1 extra movement this post.</p><p>Your movement ignores difficult terrain (impassable terrains are excluded).</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "taunt",
    name: "Taunt",
    color: "#d78747",
    image: "https://terrarp.com/db/action/taunt.png",
    description: "<p>Enemies are more likely to attack you this cycle. You can indicate if 'Taunt' is on or off in your post without using an action.</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "guard",
    name: "Guard",
    color: "#d78747",
    image: "https://terrarp.com/db/action/guard.png",
    description: "<p>Cautiously attack the enemy and gain the Guarded status.</p>",
    dice: "2d20 + modifiers",
    roll: "?r guard<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura dynamism hyper-sense summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "hinder",
    name: "Hinder",
    color: "#d78747",
    image: "https://terrarp.com/db/action/hinder.png",
    description: "<p>Attack and hinder the target. Half of the attack's final roll result reduces the target's HP, the other half reduces the target's Stability.</p>",
    dice: "1d100 + modifiers",
    roll: "?r hinder<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph slash weapon-arts",
    category: "normal"
  },
  {
    lookup: "protect",
    name: "Protect",
    color: "#d78747",
    image: "https://terrarp.com/db/action/protect.png",
    description: "<p>Attack a target and give 1 nearby ally the Protected status.</p>",
    dice: "2d20 + modifiers",
    roll: "?r protect<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "ultra-hinder",
    name: "Ultra Hinder",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uhinder.png",
    description: "<p><i>(Special Action)</i></p><p>Perform a big attack and majorly hinder the target at the cost of your own safety.Half of the attack's final roll result reduces the target's HP, the other half reduces the target's Stability.</p><p>Gain the Vulnerable status. If you roll one nat100, double your total after adding modifiers. If you roll two nat100s, multiply your total by 5.</p>",
    dice: "2d100 + modifiers",
    roll: "?r ultrahinder<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph slash weapon-arts",
    category: "normal"
  },
  {
    lookup: "ultra-protect",
    name: "Ultra Protect",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uprotect.png",
    description: "<p><i>(Special Action)</i></p><p>Perform a big attack that damage the enemy and protect nearby allies. Give 3 allies in the same zone the Protected status.</p><p>Gain the Vulnerable status. If you roll a nat100, double your total after adding modifiers.</p>",
    dice: "1d100 + modifiers",
    roll: "?r ultraprotect<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "steady",
    name: "Steady",
    color: "#d84848",
    image: "https://terrarp.com/db/action/steady.png",
    description: "<p>Execute an attack with higher base damage, but does not have critical.</p>",
    dice: "6d20 + modifiers",
    roll: "?r steady<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits corrupt evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "reckless",
    name: "Reckless Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/reckless.png",
    description: "<p><i>(Special Action)</i></p><p>Extend yourself and execute a powerful reckless attack with high unpredictability and high payoff.</p><p>Gain the Vulnerable status. If you roll one nat100, double your total after adding modifiers. If you roll two nat100s, multiply your total by 5.</p>",
    dice: "2d100 + modifiers",
    roll: "?r reckless<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "aura battle-spirits corrupt dynamism evoke mend metamorph summon crush-weapons martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "burst",
    name: "Burst Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/burst.png",
    description: "<p><i>(Special Action)</i></p><p>Execute an attack that can deal massive damage at the cost of your safety.</p><p>Gain the Vulnerable status.<p>",
    dice: "2d20 per mastery rank + 1d20 per weapon rank",
    roll: "?r burst<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "aeromancy crush-weapons dark-magic pyromancy slash-weapons battle-spirits corrupt dynamism evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "critical",
    name: "Critical Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/critical.png",
    description: "<p><i>(Special Action)</i></p><p>Execute an attack that exploits the target's weak point and leave them devastated when you land a critical at the cost of your safety.</p><p>Gain the Vulnerable status. As your rank in the corresponding mastery increases, so does your critical range. If you roll naturally in your critical range, double your total damage after adding modifiers.</p>",
    dice: "2d100 with advantage + modifiers",
    roll: "?r critical<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "aeromancy dark-magic martial-arts pierce-weapons ranged-weapons shadow-arts battle-spirits corrupt dynamism evoke hyper-sense metamorph weapon-arts",
    category: "normal"
  },
  {
    lookup: "revive",
    name: "Revive",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/revive.png",
    description: "<p>Revive a dead character.</p><p>Every nat20 increases the number of targets you can revive by 1.</p>",
    dice: "1d20 per mastery rank",
    roll: "?r revive<span class='masteryreplace'> MR </span># character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "heal",
    name: "Heal",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/heal.png",
    description: "<p>Heal yourself or another target.</p><p><i>(Single) </i>Heal 1 target for the full amount</p><p>OR</p><p><i>(AoE) </i>Split your heal amount equally among three targets, rounded down.</p>",
    dice: "1d20 + modifiers",
    roll: "?r heal single/aoe<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "buff",
    name: "Buff",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/buff.png",
    description: "<p>Grant yourself or another target a damage buff.</p><p><i>(Single) </i>Give one target a damage buff that lasts 3 posts</p><p>OR</p><p><i>(AoE) </i>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "1d20 + modifiers / 3",
    roll: "?r buff single/aoe<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "cleanse",
    name: "Cleanse",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/cleanse.png",
    description: "<p>Remove bad conditions from yourself or your target. You can remove up to 1d4 +<span class='masteryreplace'> MR </span>stacks of conditions.</p><p><i>(Single) </i>Dispel conditions from your target.</p><p>OR</p><p><i>(AoE) </i>Divide your cleanses between up to 3 targets (unequal distribution is okay)</p>",
    dice: "1d4 + MR",
    roll: "?r cleanse<span class='masteryreplace'> MR </span># character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "power-heal",
    name: "Power Heal",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pheal.png",
    description: "<p><i>(Special Action)</i></p><p>Heal yourself or another target.<p>This is a more potent heal with dangerous drawbacks.</p><p>Gain the Vulnerable status. If you roll a nat100, double your total after adding modifiers.</p><p><i>(Single) </i>Heal 1 target for the full amount</p><p>OR</p><p><i>(AoE) </i>Split your heal amount equally among three targets, rounded down.</p>",
    dice: "1d100 + modifiers",
    roll: "?r powerheal single/aoe<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "power-buff",
    name: "Power Buff",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pbuff.png",
    description: "<p><i>(Special Action)</i></p><p>Grant yourself or another target a damage buff.This is a more potent buff with dangerous drawbacks.</p><p>Gain the Vulnerable status.</p><p><i>(Single) </i>Give one target a damage buff that lasts 3 posts</p><p>OR</p><p><i>(AoE) </i>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "1d100 + modifiers / 3",
    roll: "?r powerbuff single/aoe<span class='masteryreplace'> MR </span>WR # character-name/thread-code",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "defense-enhancement",
    name: "Defense Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/defense.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery makes you more resilient to damage. Add 5 per mastery rank (up to a max of 25) to your HP.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura hyper-sense",
    category: "passive"
  },
  {
    lookup: "damage-enhancement",
    name: "Damage Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/damage.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery enhances your attacks. Add 3 per mastery rank (up to a max of 15) to all standard and special attacks.</p>",
    dice: "-",
    roll: "-",
    masteries: "battle-spirits corrupt evoke hyper-sense metamorph summon weapon-arts",
    category: "passive"
  },
  {
    lookup: "support-enhancement",
    name: "Support Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/support.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery enhances your healing and buffing supportive abilities. Add 3 per mastery rank (up to a max of 15) to standard and special heal and buff.</p>",
    dice: "-",
    roll: "-",
    masteries: "corrupt evoke mend",
    category: "passive"
  },
  {
    lookup: "dynamic-maneuver",
    name: "Dynamic Maneuver",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/maneuver.png",
    description: "<p><i>(Passive)</i></p><p>At D-rank, gain 1 extra movement per post (stackable with Speed Enhancement). Your movement ignores difficult terrain (impassable terrains are excluded).<br>In addition, you can move through monster zones, but you cannot end your turn there.</p>",
    dice: "-",
    roll: "-",
    masteries: "battle-spirits dynamism",
    category: "passive"
  },
  {
    lookup: "dynamic-utility",
    name: "Dynamic Utility",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/utility.png",
    description: "<p><i>(Passive)</i></p><p>At C-rank, gain 1 extra movement per post (stackable with Speed Enhancement).<br>In addition, you can choose up to 2 willing targets in the same zone as you to move with you. They must end their movement at the same place as you. 1 movement is required for each person moving this way, including yourself.</p>",
    dice: "-",
    roll: "-",
    masteries: "metamorph dynamism",
    category: "passive"
  },
  {
    lookup: "speed-enhancement",
    name: "Speed Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/speed.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery grants you unrivaled speed and mobility. Your mastery grants you incredible speed. Gain extra movement at B (+1), A (+2), and S (+3).</p>",
    dice: "-",
    roll: "-",
    masteries: "dynamism",
    category: "passive"
  },
  {
    lookup: "alter-hinder",
    name: "Alter Hinder",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/alter-hinder.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery grants your Hinder and Ultra Hinder actions more flexibility. Instead of splitting the damage evenly between the enemy's HP and its Stability, you can pick which of the two to use your full roll result on.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura summon weapon-arts",
    category: "passive"
  },
]
