const actionlist = [
  {
    lookup: "attack",
    name: "Normal Attack",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/attack.png",
    description: "<p>A spell, physical, or combo attack flavored by your mastery.</p><p>On a natural 100, double your total after adding modifiers.</p>",
    dice: "1d100 + modifiers",
    roll: "?r attack <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "recover",
    name: "Recover",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/recover.png",
    description: "<p>Recover HP.</p>",
    dice: "1d20",
    roll: "?r recover # Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "rush",
    name: "Rush",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/rush.png",
    description: "<p>You focus all your effort into moving. Gain 1 extra movement this post.</p><p>Your movement ignores difficult terrain (impassable terrains are excluded).</p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "taunt",
    name: "Taunt",
    color: "#d78747",
    image: "https://terrarp.com/db/action/taunt.png",
    description: "<p>Enemies are more likely to attack you this cycle. You can indicate if 'Taunt' is on or off in your post without using an action.</p><p><i>This action can be flavored as verbal insults, threaten, taunt aura, using a skill with your mastery to grab the enemy's attention, or simply throwing the enemy a mean stare.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "guard",
    name: "Guard",
    color: "#d78747",
    image: "https://terrarp.com/db/action/guard.png",
    description: "<p>Attack the enemy with your guard up and gain the Guarded status.</p><p><i>This action can be flavored as an attack or a spell that does damage and also reduces incoming damage or increases your defense. You can also flavor Guard as a defensive attack.</i></p>",
    dice: "2d20 + modifiers",
    roll: "?r guard <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura dynamism hyper-sense summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "hinder",
    name: "Hinder",
    color: "#d78747",
    image: "https://terrarp.com/db/action/hinder.png",
    description: "<p>Attack and hinder the target. Half of the attack's final roll result reduces the target's HP, the other half reduces the target's stability/SP.</p><p><i>This action can be flavored as a spell or ability that crowd controls (CC) the enemy such as entanglement, cripple, slow, disrupt, trap, etc.</i></p>",
    dice: "1d100 + modifiers",
    roll: "?r hinder <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph slash weapon-arts",
    category: "normal"
  },
  {
    lookup: "protect",
    name: "Protect",
    color: "#d78747",
    image: "https://terrarp.com/db/action/protect.png",
    description: "<p>Attack a target and give 1 nearby ally the Protected status.</p><p><i>This action can be flavored as a taunt that draws enemy attention away to reduce damage, an ability or spell that damages the enemy and boost your ally's defense, or an ability that stops enemies from getting close to the ally, etc.</i></p>",
    dice: "2d20 + modifiers",
    roll: "?r protect <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "ultra-hinder",
    name: "Ultra Hinder",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uhinder.png",
    description: "<p><i>(Special Action)</i></p><p>Perform a big attack and majorly hinder the target at the cost of your own safety. Half of the attack's final roll result reduces the target's HP, the other half reduces the target's Stability. Gain the Vulnerable status.</p><p><i>This action can be flavored as a spell or ability that crowd controls (CC) the enemy such as entanglement, cripple, slow, disrupt, trap, etc.</i></p>",
    dice: "2d100 + modifiers",
    roll: "?r ultrahinder <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph slash weapon-arts",
    category: "normal"
  },
  {
    lookup: "ultra-protect",
    name: "Ultra Protect",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uprotect.png",
    description: "<p><i>(Special Action)</i></p><p>Perform a big attack that damage the enemy and protect nearby allies. Give 3 allies in the same zone the Protected status and gain the Vulnerable status.</p><p><i>You can flavor this action as a form of taunt to draw enemy attention onto yourself, an ability or spell that deals damage and protects at the same time, something that lessenns the enemy's damage, etc.</i></p>",
    dice: "1d100 + modifiers",
    roll: "?r ultraprotect <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "movement-enhancement",
    name: "Movement Enhancement",
    color: "#d84848",
    image: "https://terrarp.com/db/action/extension.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery increases your movement potential. From C-rank, your movement increases by 1.</p><p><i>This passive can be flavored as having great athleticism or your mastery actively enhancing your movement in some way.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "passive"
  },
  {
    lookup: "steady",
    name: "Steady",
    color: "#d84848",
    image: "https://terrarp.com/db/action/movement.png",
    description: "<p>Execute an attack with higher base damage, but does not have critical.</p><p><i>You can flavor this action as a tactical strike, a dependable combo of attacks that works, etc.</i></p>",
    dice: "6d20 + modifiers",
    roll: "?r steady <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits corrupt evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "reckless",
    name: "Reckless Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/reckless.png",
    description: "<p><i>(Special Action)</i></p><p>Extend yourself and execute a powerful reckless attack with high unpredictability and high payoff. You become Vulnerable.</p><p><i>You can flavor this action as using powerful abilities or spells close to the enemy, positioning yourself in a compromising location for better aim, etc.</i></p>",
    dice: "2d100 + modifiers",
    roll: "?r reckless <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aura battle-spirits corrupt dynamism evoke mend metamorph summon crush-weapons martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "burst",
    name: "Burst Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/burst.png",
    description: "<p><i>(Special Action)</i></p><p>Execute an attack that can deal massive damage at the cost of your safety. You become Vulnerable.</p><p><i>You can flavor this action as a high-level destructive spell, a deadly special attack, a combo chain, etc.</i><p>",
    dice: "2d20 per mastery rank + 1d20 per weapon rank",
    roll: "?r burst <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy crush-weapons dark-magic pyromancy slash-weapons battle-spirits corrupt dynamism evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "critical",
    name: "Critical Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/critical.png",
    description: "<p><i>(Special Action)</i></p><p>Execute an attack that exploits the target's weak point and leave them devastated when you land a critical at the cost of your safety. You become Vulnerable.</p><p><i>You can flavor this action as a repositioning ability that allows you to capitalize on the target's mistake, a spell that targets their weak point, using improved aiming to land a potent attack, etc.</i></p>",
    dice: "2d100 with advantage + modifiers",
    roll: "?r critical <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy dark-magic martial-arts pierce-weapons ranged-weapons shadow-arts battle-spirits corrupt dynamism evoke hyper-sense metamorph weapon-arts",
    category: "normal"
  },
  {
    lookup: "revive",
    name: "Revive",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/revive.png",
    description: "<p>Bring a player back to life within 10 minutes of death. You need their permission OOCly, but they have no say ICly. The target will come back with 75 HP. A player may only be revived twice per thread.</p><p><i>You can flavor this action as a typical holy revive spell, a potion that brings your target back from death, a spell that calls the soul back to the body and reconstruct it, etc.</i></p>",
    dice: "1d20 per mastery rank",
    roll: "?r revive <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "heal",
    name: "Heal",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/heal.png",
    description: "<p>Heal yourself or another target.</p><p><i>This action can be flavored as any ability or effect that helps keep the targets alive such as barrier, shielding, heal-over-time, life transference, etc.</i></p><p span class='single' onclick='targetReplaceSingle(this)'><i>(Single) </i>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><i>(AoE) </i>Split your heal amount equally among three targets, rounded down.</p>",
    dice: "1d20 + modifiers",
    roll: "?r heal <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "buff",
    name: "Buff",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/buff.png",
    description: "<p>Grant yourself or another target a damage buff.</p><p><i>This action can be flavored as you magically empowering the target's weapon, setting them up to do more damage, etc.</i></p><p span class='single' onclick='targetReplaceSingle(this)'><i>(Single) </i>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><i>(AoE) </i>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "1d20 + modifiers / 3",
    roll: "?r buff <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "dispel",
    name: "Dispel",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/dispel.png",
    description: "<p>Remove bad conditions from yourself or your target. You can remove up to 1d4 + MR stacks of conditions.</p><p><i> This action can be flavored as a standard dispel or you doing something more active to clear conditions.</i></p><p><i>(Single) </i>Dispel conditions from your target.</p><p><i>(AoE) </i>Divide your cleanses between up to 3 targets (unequal distribution is okay)</p>",
    dice: "1d4 + MR",
    roll: "?r dispel <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "power-heal",
    name: "Power Heal",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pheal.png",
    description: "<p><i>(Special Action)</i></p><p>Heal yourself or another target. This is a more potent heal with dangerous drawbacks. You become Vulnerable.</p><p><i>This action can be flavored as any ability or effect that helps keep the targets alive such as barrier, shielding, heal-over-time, life transference, etc.</i></p><p span class='single' onclick='targetReplaceSingle(this)'><i>(Single) </i>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><i>(AoE) </i>Split your heal amount equally among three targets, rounded down.</p>",
    dice: "1d100 + modifiers",
    roll: "?r powerheal <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "power-buff",
    name: "Power Buff",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pbuff.png",
    description: "<p><i>(Special Action)</i></p><p>Grant yourself or another target a damage buff. This is a more potent buff with dangerous drawbacks. You become Vulnerable.</p><p><i>This action can be flavored as you magically empowering the target's weapon, setting them up to do more damage, etc.</i></p><p span class='single' onclick='targetReplaceSingle(this)'><i>(Single) </i>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><i>(AoE) </i>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "1d100 + modifiers / 3",
    roll: "?r powerbuff <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "defense-enhancement",
    name: "Defense Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/defense.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery makes you more resilient to damage. Add 10 per mastery rank (up to a max of 50) to your HP.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura battle-spirits hyper-sense summon",
    category: "passive"
  },
  {
    lookup: "damage-enhancement",
    name: "Damage Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/damage.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery enhances your attacks. Add 3 per mastery rank (up to a max of 15) to all standard and special attacks.</p>",
    dice: "-",
    roll: "-",
    masteries: "battle-spirits corrupt evoke hyper-sense metamorph summon weapon-arts",
    category: "passive"
  },
  {
    lookup: "support-enhancement",
    name: "Support Enhancement",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/support.png",
    description: "<p><i>(Passive)</i></p><p>Your Alter Mastery enhances your healing and buffing supportive abilities. Add 3 per mastery rank (up to a max of 15) to standard and special heal and buff.</p>",
    dice: "-",
    roll: "-",
    masteries: "corrupt evoke mend",
    category: "passive"
  },
  {
    lookup: "maneuver",
    name: "Maneuver",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/maneuver.png",
    description: "<p><i>(Passive)</i></p><p>From D-rank, your movement increases by 1. Your movement ignores the difficult terrain effect. Also, you can move through monster zones as though they are regular zone.</p>",
    dice: "-",
    roll: "-",
    masteries: "dynamism metamorph",
    category: "passive"
  },
  /*{
    lookup: "ferrier",
    name: "Ferrier",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/ferrier.png",
    description: "<p><i>(Passive)</i></p><p>From C-rank, your movement increases by 1. In addition, you can choose up to 2 willing targets in the same zone to move with you, stopping where you do without spending their movement. Reduce your movement by 1 for every person that moving in this way, including yourself.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura metamorph dynamism",
    category: "passive"
  },*/
  {
    lookup: "speed-up",
    name: "Speed Up",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/speed.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery grants you unrivaled speed and mobility. Your mastery grants you incredible speed. Gain extra movement at B (+1), A (+2), and S (+3).</p>",
    dice: "-",
    roll: "-",
    masteries: "dynamism",
    category: "passive"
  },
  {
    lookup: "alter-hinder",
    name: "Alter Hinder",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/alter-hinder.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery grants your Hinder and Ultra Hinder actions more flexibility. Instead of splitting the damage evenly between the enemy's HP and its Stability, you can pick which of the two to use your full roll result on.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura weapon-arts",
    category: "passive"
  },
  {
    lookup: "alter-dispel",
    name: "Alter Dispel",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/alter-dispel.png",
    description: "<p><i>(Passive)</i></p><p>This passive enhances the Dispel action. When you Dispel, use 2d4. Also, you can now dispel specific enemy's buffs and certain zone effects in addition to ally's conditions. You can only choose to dispel one type of target at a time (allies' conditions, enemies' buffs, or zone effects).</p>",
    dice: "-",
    roll: "-",
    masteries: "mend",
    category: "passive"
  },
  /*{
    lookup: "extension",
    name: "Extension",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/extension.png",
    description: "<p><i>(Passive)</i></p><p>At C-rank, your actions (excluding those with the Self-targeted tag) can target an ally or enemy 1 zone away. At S-rank, this range increases to 2.</p>",
    dice: "-",
    roll: "-",
    masteries: "hyper-sense summon weapon-arts",
    category: "passive"
  },*/
]
