const actionlist = [
  {
    lookup: "attack",
    name: "Normal Attack",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/attack.png",
    description: "<p>Perform a basic attack.</p><p><i>You can flavor this action as a spell, a weapon attack, or a damaging ability flavored by your mastery.</i></p>",
    dice: "1d100 + modifiers",
    roll: "?r attack <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "recover",
    name: "Recover",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/recover.png",
    description: "<p>Recover your HP by 1d20. This roll cannot be modified by any passive or bonus action.</p><p><i>You can flavor this action as taking a breather, patching up a wound, drinking a potion, calming down, etc.</i></p>",
    dice: "1d20",
    roll: "?r recover # Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "rush",
    name: "Rush",
    color: "#b0b0b0",
    image: "https://terrarp.com/db/action/rush.png",
    description: "<p>Spend your action to double your movement this cycle.</p><p><i>This can be flavored you focusing on moving and gaining extra speed.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons",
    category: "normal"
  },
  {
    lookup: "taunt",
    name: "Taunt",
    color: "#d78747",
    image: "https://terrarp.com/db/action/taunt.png",
    description: "<p>When you perform an attack action, you may activate taunt to gain the Taunting State.</p><p><b>Passive.</b> Your maximum HP is increased by 25. Having Taunt in your build makes you susceptible to Taunt Buster attacks.</p><p><i>This action can be flavored as sprouting insults, threatening, imposing a taunting aura, throwing the target a mean stare, or using your mastery to attract enemies' attention while dealing damage.</i></p>",
    dice: "-",
    roll: "[taunt]taunt[/taunt]",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura",
    category: "normal"
  },
  {
    lookup: "counter",
    name: "Counter",
    color: "#d78747",
    image: "https://terrarp.com/db/action/counter.png",
    description: "<p>Time a counter attack. If successful, your attack deals an extra 20 damage and you may reduce an incoming damage source by 10 this cycle (the reduction applies before Multipliers). If unsuccessful, this action becomes a normal attack.</p><p><i>This action can be flavored as a defensive attack, a counterstrike, or a spell that does damage and also reduces incoming damage.</i></p>",
    dice: "1d100 + modifiers<br><b>Success:</b> 85+ at D-rank, 70+ (C), 55+ (B), 40+ (A), 25+ (S)",
    roll: "?r counter <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense weapon-arts",
    category: "normal"
  },
  {
    lookup: "hinder",
    name: "Hinder",
    color: "#d78747",
    image: "https://terrarp.com/db/action/hinder.png",
    description: "<p>Perform an attack that hinders and damages your target. Divide your attack by 2 to reduce both the target's HP and SP equally.</p><p>This action can be flavored as a crowd control (CC) ability or spell such as entanglement, cripple, slow, disrupt, trap, blind, or other effects that hinder your target.</p>",
    dice: "1d100 + modifiers",
    roll: "?r hinder <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph weapon-arts",
    category: "normal"
  },
  {
    lookup: "protect",
    name: "Protect",
    color: "#d78747",
    image: "https://terrarp.com/db/action/protect.png",
    description: "<p>Perform a defensive attack and give 1 ally in the same zone the Protected status.</p><p><i>This action can be flavored as an ability that draws enemies' attention away from allies, a powerful spell that damages an enemy and boosts your allies' defense, or a power that prevents enemies from getting close to the ally, etc.</i></p>",
    dice: "1d100 + modifiers",
    roll: "?r protect <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  {
    lookup: "ultra-hinder",
    name: "Ultra Hinder",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uhinder.png",
    description: "<p><i>(Special Attack)</i></p><p>Perform a risky ultra attack that greatly hinders and damages your target. Divide your attack by 2 to reduce both the target's HP and SP equally. Gain the Vulnerable State.</p><p><i>This action can be flavored as a crowd control (CC) ability or spell such as entanglement, cripple, slow, disrupt, trap, blind, or other effects that hinder your target.</i></p>",
    dice: "2d100 + modifiers",
    roll: "?r ultrahinder <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons aura battle-spirits corrupt dynamism evoke hyper-sense metamorph weapon-arts",
    category: "normal"
  },
  {
    lookup: "ultra-protect",
    name: "Ultra Protect",
    color: "#da6c41",
    image: "https://terrarp.com/db/action/uprotect.png",
    description: "<p><i>(Special Attack)</i></p><p>Perform a risky ultra defensive attack and give 3 allies in the same zone the Protected status. Gain the Vulnerable State.</p><p><i>This action can be flavored as an ability that draws enemies' attention away from allies, a powerful spell that damages an enemy and boosts your allies' defense, or a power that prevents enemies from getting close to the ally, etc.</i></p>",
    dice: "1d100 + modifiers",
    roll: "?r ultraprotect <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "arcanamancy astramancy beast-arts geomancy guard-arts hemomancy hydromancy illusion-magic aura hyper-sense",
    category: "normal"
  },
  /*{
    lookup: "extra-movement",
    name: "Extra Movement",
    color: "#d84848",
    image: "https://terrarp.com/db/action/movement.png",
    description: "<p><i>(Passive)</i></p><p>Your mastery increases your movement potential. Your movement increases by 1.</p><p><i>This passive can be flavored as having great athleticism or your mastery actively enhancing your movement in some way.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits dynamism metamorph",
    category: "passive"
  },*/
  {
    lookup: "heavy",
    name: "Heavy Attack",
    color: "#d84848",
    image: "https://terrarp.com/db/action/hattack.png",
    description: "<p>Perform a heavy attack. You cannot move next cycle (being moved is okay). This attack increases your chance of being targeted.</p><p><i>You can flavor this action as an attack that has some kind of cooldown, or one that disrupts your movement ability, or one that requires you to set up in a zone.</i></p>",
    dice: "1d100 + Power Bonus + modifiers<br><b>Power Bonus:</b> +10 at D-rank, +20 (B), +30 (S)",
    roll: "?r heavy <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits corrupt evoke metamorph",
    category: "normal"
  },
  {
    lookup: "steady",
    name: "Steady Attack",
    color: "#d84848",
    image: "https://terrarp.com/db/action/steady.png",
    description: "<p>Perform an attack with reliable damage.</p><p><i>You can flavor this action as a tactical strike, a reliable attack combo or spell with consistent damage, etc.</i></p>",
    dice: "6d20 + modifiers<br><b>Crit:</b> Each nat-20 will grant you another d20 roll",
    roll: "?r steady <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits corrupt dynamism evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "reckless",
    name: "Reckless Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/reckless.png",
    description: "<p><i>(Special Attack)</i></p><p>Perform a powerful reckless attack with high-risk and high-reward. When you get a nat-200 (100, 100), multiply the final roll result by 7. Gain the Vulnerable State.</p><p><i>You can flavor this action as a high powerful attack that requires you to be close to the enemy, a potent spell that could harm you in its radius, an ability that requires risky positioning to execute, etc.</i></p>",
    dice: "2d100 + modifiers",
    roll: "?r reckless <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "crush-weapons martial-arts pierce-weapons pyromancy ranged-weapons shadow-arts slash-weapons battle-spirits corrupt dynamism evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "burst",
    name: "Burst Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/burst.png",
    description: "<p><i>(Special Attack)</i></p><p>Perform a risky explosive attack that can deal massive damage. Instead of d100, roll Xd20. In addition, deal 20 damage to all enemy adjacent to your target. Gain the Vulnerable State.</p><p><i>You can flavor this action as a high-level destructive spell, a deadly special attack, a combo chain, etc.</i></p>",
    dice: "8d20 + 1d20 per mastery rank and weapon rank + buff/other modifiers",
    roll: "?r burst <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy crush-weapons dark-magic martial-arts pyromancy slash-weapons battle-spirits corrupt dynamism evoke metamorph summon weapon-arts",
    category: "normal"
  },
  {
    lookup: "critical",
    name: "Critical Attack",
    color: "#c72828",
    image: "https://terrarp.com/db/action/critical.png",
    description: "<p><i>(Special Attack)</i></p><p>Perform a risky critical attack with Advantage Instead of critting on a nat-100, your crit range is expanded. When critting, multiply your roll result by 3. Gain the Vulnerable State.</p><p><i>You can flavor this action as an attack that exposes the enemy's weak point, repositioning, capitalizing on the enemy's mistake, a backstab, a deadly direct damage spell, etc.</i></p>",
    dice: "2d100 with advantage + modifiers<br><b>Crit Range:</b> 97+ at D-rank, 94+ (C), 91+ (B), 88+ (A), 85+ (S)",
    roll: "?r critical <span class='masteryreplace'>MR</span> WR <span class='damagepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aeromancy dark-magic pierce-weapons ranged-weapons shadow-arts battle-spirits corrupt dynamism evoke hyper-sense metamorph weapon-arts",
    category: "normal"
  },
  {
    lookup: "revive",
    name: "Revive",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/revive.png",
    description: "<p>Bring a player back to life with 50 HP. Players may only be revived twice per thread.</p><p><i>Narratively, revives only work on players who have died within the last 10 minutes. The person being revived cannot stop of the revival. You can flavor this action as a typical holy resurrect, a potion that brings your target back from death, a spell that calls the soul back to the body and reconstruct it, etc.</i></p>",
    dice: "1d20 per mastery rank<br><b>Crit:</b> +1 revive target each time you roll a nat-20",
    roll: "?r revive <span class='masteryreplace'>MR</span> # <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "heal",
    name: "Heal",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/heal.png",
    description: "<p>Perform a heal on yourself and allies.</p><p><i>This action can be flavored as an ability or a spell that keeps the targets alive such as barrier, shielding, heal-over-time, life transference, etc.</i></p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Split your heal evenly among 3 targets</p>",
    dice: "1d20 + modifiers",
    roll: "?r heal <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
    category: "normal"
  },
  {
    lookup: "buff",
    name: "Buff",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/buff.png",
    description: "<p>Grant yourself and allies a damage buff. If you have more than 1 buff, only the latest one will apply. Buffs expire whenever you post even when you don't attack.</p><p><i>This action can be flavored as you magically empowering the target in some way, setting them up to do more damage, guiding their strike, etc.</i></p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "1d100 + modifiers / 3",
    roll: "?r buff <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
    category: "normal"
  },
  {
    lookup: "dispel",
    name: "Dispel",
    color: "#4e9be2",
    image: "https://terrarp.com/db/action/dispel.png",
    description: "<p>Remove harmful conditions from yourself and others. Dispel can also remove certain environmental effects. You can distribute X charges of Dispel however you like up to 3 targets.</p><p><i>This action can be flavored as a standard cleanse or your character actively doing something to clear detrimental conditions and effects.</i></p>",
    dice: "1d4 + MR",
    roll: "?r dispel <span class='masteryreplace'>MR</span> <span class='dispelpassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend",
    category: "normal"
  },
  {
    lookup: "power-heal",
    name: "Power Heal",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pheal.png",
    description: "<p><i>(Special Action)</i></p><p>Perform a powerful heal on yourself and allies. Gain the Vulnerable State.</p><p><i>This action can be flavored as an ability or a spell that keeps the targets alive such as barrier, shielding, heal-over-time, life transference, etc.</i></p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Heal 1 target for the full amount</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Split your heal evenly among 3 targets</p>",
    dice: "1d100 + modifiers",
    roll: "?r powerheal <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
    category: "normal"
  },
  {
    lookup: "power-buff",
    name: "Power Buff",
    color: "#3460d0",
    image: "https://terrarp.com/db/action/pbuff.png",
    description: "<p><i>(Special Action)</i></p><p>Grant yourself and allies a powerful damage buff. If you have more than 1 buff, only the latest one will apply. Buffs expire whenever you post even when you don't attack. Gain the Vulnerable State.</p><p><i>This action can be flavored as you magically empowering the target in some way, setting them up to do more damage, guiding their strike, etc.</i></p><p><b>Click one of the toggles below:</b></p><p span class='single' onclick='targetReplaceSingle(this)'><b>(Single) </b>Give one target a damage buff that lasts 3 posts</p><p span class='aoe' onclick='targetReplaceAOE(this)'><b>(AoE) </b>Give three targets a damage buff that lasts for 1 post.</p>",
    dice: "2d100 + modifiers / 3",
    roll: "?r powerbuff <span class='targetreplace'>single/aoe</span> <span class='masteryreplace'>MR</span> WR <span class='supportpassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic mend summon",
    category: "normal"
  },
  {
    lookup: "inspire",
    name: "Inspire",
    color: "rgb(78, 155, 226)",
    image: "https://terrarp.com/db/action/inspire.png",
    description: "<p>Inspire or help allies. Give 3 targets a +X bonus to any mastery check, expertise check, or contribution roll they are attempting. Inspire lasts 1 cycle and does not affect Saves.</p><p><i>This action can be flavored as having an inspiring presence or actively helping others achieve specific tasks through your masteries.</i></p>",
    dice: "1d6 per MR",
    roll: "?r inspire <span class='masteryreplace'>MR</span> <span class='inspirepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic aura mend summon",
    category: "normal"
  },
  {
    lookup: "haste",
    name: "Haste",
    color: "rgb(78, 155, 226)",
    image: "https://terrarp.com/db/action/haste.png",
    description: "<p>Increase yours and other's movements. You can distribute X movements however you like up to 3 targets. The movement boost lasts 1 cycle.</p><p><i>This action can be flavored as a spell that speed up your ally, increasing morale to raise their speed, etc.</i></p>",
    dice: "1d6",
    roll: "?r haste <span class='hastepassivemod'># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "alchemy animancy chronomancy divine-magic harmonic-magic magitech nature-magic spirit-magic dynamism mend",
    category: "normal"
  },
  {
    lookup: "defense",
    name: "Defense",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/defense.png",
    description: "<p><i>(Passive)</i></p><p>You are more resilient to damage and pain. Your maxium HP increases by 10 per mastery rank.</p><p><i>This passive can be flavored as your Hyper Sense allowing you to avoid incoming attacks or your Aura/Metamorph form increasing your defense, etc.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "aura hyper-sense metamorph",
    category: "passive"
  },
  {
    lookup: "damage",
    name: "Damage",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/damage.png",
    description: "<p><i>(Passive)</i></p><p>You gain incredible power. All attack actions gain a bonus of +5 per alter mastery rank (before multipliers).</p><p><i>This passive can be flavored as your bonded weapon enabling you to deal more damage (Weapon Arts), your empowered form (Battle Spirits) increasing your damage potential, etc.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "battle-spirits corrupt hyper-sense weapon-arts",
    category: "passive"
  },
  {
    lookup: "support",
    name: "Support",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/support.png",
    description: "<p><i>(Passive)</i></p><p>Your alter mastery makes your supportive abilities much more potent. All heal and buff actions gain a bonus of +5 per alter mastery rank (before multipliers). Inspire and Dispel gain a +5 bonus. Haste gains a +1 bonus.</p><p><i>This passive can be flavored as something like Mend boosting your supportive spells or Corrupt granting you a magical boost to supportive ability by tapping into dark elements.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "corrupt evoke mend summon",
    category: "passive"
  },
  /*{
    lookup: "maneuver",
    name: "Maneuver",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/maneuver.png",
    description: "<p><i>(Passive)</i></p><p>From D-rank, your movement increases by 1. Your movement ignores the difficult terrain effect. Also, you can move through monster zones as though they are regular zone.</p>",
    dice: "-",
    roll: "-",
    masteries: "battle-spirits dynamism",
    category: "passive"
  },*/
  /*{
    lookup: "ferrier",
    name: "Ferrier",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/ferrier.png",
    description: "<p><i>(Passive)</i></p><p>From C-rank, your movement increases by 1. In addition, you can choose up to 2 willing targets in the same zone to move with you, stopping where you do without spending their movement. Reduce your movement by 1 for every person that moving in this way, including yourself.</p>",
    dice: "-",
    roll: "-",
    masteries: "aura metamorph dynamism",
    category: "passive"
  },*/
  {
    lookup: "speed",
    name: "Speed",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/speed.png",
    description: "<p><i>(Passive)</i></p><p>You gain incredible speed. You gain +1 movement at D, C, and B-rank. In addition, you gain +5 to reflex at A and S-rank (max: +3 movement and +10 reflex).</p><p><i>You can flavor this passive as raw speed or unique movement abilities flavored by the combination of your mastery.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "dynamism evoke metamorph",
    category: "passive"
  },
  {
    lookup: "alter-hinder",
    name: "Alter Hinder",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/alter-hinder.png",
    description: "<p><i>(Passive)</i></p><p>You gain better control of your hinder abilities, granting you more versatility. When performing a Hinder or Ultra Hinder attack, you may damage HP or SP exclusively or split the damage evenly after you roll.</p><p><i>This passive can be flavored as a unique skill that let you damage or hinder enemies (Battle Spirits), a tactical setup (Aura), a dynamic weapon with multiple modes (Weapon Arts), etc.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "aura battle-spirits weapon-arts",
    category: "passive"
  },
  {
    lookup: "extension",
    name: "Extension",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/extension.png",
    description: "<p><i>(Passive)</i></p><p>You have further reach than others. Your actions can target allies or enemies that are 1 zone away, diagonal included.</p><p><i>Narratively, you do not need this passive to be a ranged combatant since each zone on a battlemap is often very large. You can flavor this passive as your character having Summons that can act independently away from you or having incredible aim that let you perform actions from a long distance away (Hyper Sense).</i></p>",
    dice: "-",
    roll: " | Extension",
    masteries: "hyper-sense mend summon",
    category: "passive"
  },
  {
    lookup: "carry",
    name: "Carry",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/carry.png",
    description: "<p><i>(Bonus Action)</i></p><p>You can take allies with you while moving. When you move, you can pickup one willing ally on any zone you move through and drop them off at any zone you enter afterward.</p><p><i>You can flavor this bonus action as your Metamorphed form allowing you to carry your target from one zone to another.</i></p>",
    dice: "-",
    roll: "[carry]@Name from E1 to E4[/carry]",
    masteries: "dynamism metamorph",
    category: "passive"
  },
  /*{
    lookup: "alter-inspire",
    name: "Alter Inspire",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/alter-inspire.png",
    description: "<p>Greatly inspire allies. Give 3 targets a bonus toward any mastery or expertise check. Each target gains Xd8 (1d8 per MR) to a check (save not included) this cycle.</p>",
    dice: "1d8 per MR",
    roll: "?r alterinspire <span class='masteryreplace'>MR</span> <span class='inspirepassivemod'></span># <span class='mnamereplace'>Mastery</span> | Character Name | <span class='thrcode'>Thread Code</span>",
    masteries: "aura",
    category: "normal"
  },*/
  {
    lookup: "exceed",
    name: "Exceed",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/exceed.png",
    description: "<p><i>(Bonus Action)</i></p><p>Take damage to go beyond your limit. Sacrifice 5/10/15/20/25 HP to gain a +5/10/15/20/25 bonus to your action. This bonus works on all attack actions, heal, buff.</p>",
    dice: "-",
    roll: " | Exceed <span class='exceedvalue'>5</span>",
    masteries: "battle-spirits corrupt weapon-arts",
    category: "normal"
  },
  {
    lookup: "momentum",
    name: "Momentum",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/momentum.png",
    description: "<p><i>(Passive)</i></p><p>Empowers your combat ability with momentum and movement. All attack actions gain +10 damage for each zone you enter until you attack. Only movements that are forward and are in a straight line count. In addition, gain +5 damage per unused movement.</p><p><i>You can flavor this passive as your character using their Slash-Dynamism to perform a powerful teleporting blade attack, etc.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "dynamism",
    category: "passive"
  },
  {
    lookup: "save-saura",
    name: "Save Aura",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/aura.png",
    description: "<p><i>(Passive)</i></p><p>Your aura passively bolsters allies' defenses. All players in your zone gets a +5 bonus to all saves. Each Save Aura may only affect 1 zone.</p><p><i>You can flavor this passive as having a Pyromancy-Aura that surrounds an ally with protective fire, etc.</i></p>",
    dice: "-",
    roll: "[aura]YourZone[/aura]",
    masteries: "aura",
    category: "passive"
  },
  {
    lookup: "overload",
    name: "Overload",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/overload.png",
    description: "<p><i>(Passive)</i></p><p>You cannot contain your inherent power. Deal 20 damage to all enemies in zones adjacent to you. Extension has no effect on Overload.</p><p><i>You can flavor this passive as your Aeromancy-Evoke form continuously discharging lightning for example.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "evoke",
    category: "passive"
  },
  {
    lookup: "versatile",
    name: "Versatile",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/versatile.png",
    description: "<p><i>(Passive)</i></p><p>Your summons grant you increased versatility in accomplishing various tasks. When you make a Mastery Contribution roll, multiply your result by 2. You cannot get x4 when you use an Effective Mastery. In addition, when you perform a mastery check, you may roll twice and take the higher result.</p><p><i>You can flavor this passive as having an ice elemental that can help you put out fire (Hydromancy-Summons), etc.</i></p>",
    dice: "-",
    roll: "-",
    masteries: "summon",
    category: "passive"
  },
  {
    lookup: "reposition",
    name: "Reposition",
    color: "#6845a2",
    image: "https://terrarp.com/db/action/reposition.png",
    description: "<p><i>(Passive)</i></p><p>You can move 1 willing ally to an adjacent zone whenever you protect or support them. With Extension, you can instead move any adjacent ally whom you supported to your zone.</p><p><i>You can flavor this passive as using supportive abilities (Mend) that can manipulate people’s position.</i></p>",
    dice: "-",
    roll: "[reposition]@Name from E1 to E4[/reposition]",
    masteries: "mend",
    category: "passive"
  },
]
