var AllMasteries = [
  {
    "name": "Aeromancy",
    "idname": "Aeromancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Aeromancy.png",
    "save": "Reflex",
    "specialty": "Knack",
    "actions": ["Normal Attack","Recover","Hindering Attack", "Stable Attack","Ultra Hinder","Reckless Attack"],
  },
  {
    "name": "Alchemy",
    "idname": "Alchemy",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Alchemy.png",
    "save": "Fortitude",
    "specialty": "Knowledge",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Animancy",
    "idname": "Animancy",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Animancy.png",
    "save": "Will",
    "specialty": "Spirituality",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Arcanamancy",
    "idname": "Arcanamancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Arcanamancy.png",
    "save": "Will",
    "specialty": "Knowledge",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Astramancy",
    "idname": "Astramancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Astramancy.png",
    "save": "Will",
    "specialty": "Spirituality",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Aura",
    "idname": "Aura",
    "type": "Alter",
    "role": "Defense",
    "image": "Images/Aura.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Battle Spirit",
    "idname": "Battle-Spirit",
    "type": "Alter",
    "role": "Offense",
    "image": "Images/Battle-Spirit.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Beast Arts",
    "idname": "Beast-Arts",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Beast-Arts.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Chronomancy",
    "idname": "Chronomancy",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Chronomancy.png",
    "save": "Reflex",
    "specialty": "Awareness",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Conjure",
    "idname": "Conjure",
    "type": "Alter",
    "role": "Offense",
    "image": "Images/Conjure.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Corrupt",
    "idname": "Corrupt",
    "type": "Alter",
    "role": "Offense",
    "image": "Images/Corrupt.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Crush Weapons",
    "idname": "Crush-Weapons",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Crush-Weapons.png",
    "save": "Fortitude",
    "specialty": "Fitness",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Burst Attack"],
  },
  {
    "name": "Dark Magic",
    "idname": "Dark-Magic",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Dark-Magic.png",
    "save": "Will",
    "specialty": "Knowledge",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Reckless Attack"],
  },
  {
    "name": "Divine Magic",
    "idname": "Divine-Magic",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Divine-Magic.png",
    "save": "Will",
    "specialty": "Presence",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Dynamism",
    "idname": "Dynamism",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Dynamism.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Evoke",
    "idname": "Evoke",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Evoke.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Geomancy",
    "idname": "Geomancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Geomancy.png",
    "save": "Fortitude",
    "specialty": "Fitness",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Guard Arts",
    "idname": "Guard-Arts",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Guard-Arts.png",
    "save": "Fortitude",
    "specialty": "Awareness",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Harmonic Magic",
    "idname": "Harmonic-Magic",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Harmonic-Magic.png",
    "save": "Will",
    "specialty": "Presence",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Hemomancy",
    "idname": "Hemomancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Hemomancy.png",
    "save": "Fortitude",
    "specialty": "Spirituality",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Hydromancy",
    "idname": "Hydromancy",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Hydromancy.png",
    "save": "Will",
    "specialty": "Knack",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Hyper Sense",
    "idname": "Hyper-Sense",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Hyper-Sense.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Illusion Magic",
    "idname": "Illusion-Magic",
    "type": "Basic",
    "role": "Defense",
    "image": "Images/Illusion-Magic.png",
    "save": "Will",
    "specialty": "Presence",
    "actions": ["Normal Attack","Recover","Guarded Attack","Protective Attack","Hindering Attack","Ultra Protect","Ultra Hinder"],
  },
  {
    "name": "Magitech",
    "idname": "Magitech",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Magitech.png",
    "save": "Reflex",
    "specialty": "Knowledge",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Martial Arts",
    "idname": "Martial-Arts",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Martial-Arts.png",
    "save": "Fortitude",
    "specialty": "Fitness",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Reckless Attack"],
  },
  {
    "name": "Mend",
    "idname": "Mend",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Mend.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Metamorph",
    "idname": "Metamorph",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Metamorph.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Nature Magic",
    "idname": "Nature-Magic",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Nature-Magic.png",
    "save": "Will",
    "specialty": "Awareness",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Pierce Weapons",
    "idname": "Pierce-Weapons",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Pierce-Weapons.png",
    "save": "Reflex",
    "specialty": "Knack",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Reckless Attack"],
  },
  {
    "name": "Pyromancy",
    "idname": "Pyromancy",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Pyromancy.png",
    "save": "Will",
    "specialty": "Presence",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Burst Attack"],
  },
  {
    "name": "Ranged Weapons",
    "idname": "Ranged-Weapons",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Ranged-Weapons.png",
    "save": "Reflex",
    "specialty": "Awareness",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Critical Attack"],
  },
  {
    "name": "Shadow Arts",
    "idname": "Shadow-Arts",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Shadow-Arts.png",
    "save": "Reflex",
    "specialty": "Knack",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Critical Attack"],
  },
  {
    "name": "Slash Weapons",
    "idname": "Slash-Weapons",
    "type": "Basic",
    "role": "Offense",
    "image": "Images/Slash-Weapons.png",
    "save": "Fortitude",
    "specialty": "Fitness",
    "actions": ["Normal Attack","Recover","Hindering Attack","Stable Attack","Ultra Hinder","Reckless Attack"],
  },
  {
    "name": "Spirit Magic",
    "idname": "Spirit-Magic",
    "type": "Basic",
    "role": "Support",
    "image": "Images/Spirit-Magic.png",
    "save": "Will",
    "specialty": "Spirituality",
    "actions": ["Normal Attack","Recover","Revive","Dispel","Heal","Buff","Power Heal","Power Buff"],
  },
  {
    "name": "Summon",
    "idname": "Summon",
    "type": "ALter",
    "role": "Support",
    "image": "Images/Summon.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  },
  {
    "name": "Weapon Arts",
    "idname": "Weapon-Arts",
    "type": "Alter",
    "role": "Support",
    "image": "Images/Weapon-Arts.png",
    "save": "N/A",
    "specialty": "N/A",
    "actions": ["Normal Attack","Recover"],
  }
]
